
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 14 19:24:15 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 27;
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 35;
  public static final int REM = 33;
  public static final int GREATER = 36;
  public static final int LPAREN = 11;
  public static final int SEMI = 7;
  public static final int CONTINUE = 18;
  public static final int LESS = 38;
  public static final int MINUS = 30;
  public static final int CHARACTER = 44;
  public static final int RPAREN = 12;
  public static final int AND = 26;
  public static final int LESSEQUAL = 39;
  public static final int OR = 25;
  public static final int BOOL = 43;
  public static final int COMMA = 8;
  public static final int INC = 23;
  public static final int DIV = 32;
  public static final int PLUS = 29;
  public static final int ASSIGN = 6;
  public static final int IF = 14;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 34;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int NUMBER = 42;
  public static final int IDENT = 41;
  public static final int BREAK = 16;
  public static final int VOID = 13;
  public static final int GREATEREQUAL = 37;
  public static final int UNION = 28;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 21;
  public static final int WHILE = 20;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 24;
  public static final int PRINT = 22;
  public static final int DO = 19;
}

